@extends('layouts.app')

@section('content')
<h1>THE MIZORAM WATER SUPPLIES (CONTROL) RULES</h1>
<p>
	<br />
	THE MIZORAM&nbsp; WATER&nbsp; SUPPLIES (CONTROL) RULES , 2006<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;In exercise of the powers confered by section 18 of the Mizoram Water Supplies (Control) Act, 2004 (No.11 of 2004) the Governor of Mizoram is pleased to make the following rules namely:-<br />
	1.&nbsp;&nbsp; &nbsp;Short title, Extent and commencement :<br />
	&nbsp;&nbsp; &nbsp;1)&nbsp;&nbsp; &nbsp;These rules may be called THE MIZORAM WATER SUPPLIES (CONTROL) RULES, 2006.<br />
	&nbsp;&nbsp; &nbsp;2)&nbsp;&nbsp; &nbsp;It shall have the like extent as the Principal Act.<br />
	&nbsp;&nbsp; &nbsp;3)&nbsp;&nbsp; &nbsp;They shall come into force on such date as the State Government may, by notification in the Official Gazette, appoint.<br />
	2.&nbsp;&nbsp; &nbsp;Definitions : &nbsp;<br />
	1)&nbsp;&nbsp; &nbsp;In these rules, unless the context otherwise requires,-<br />
	&nbsp;&nbsp; &nbsp;a)&nbsp;&nbsp; &nbsp;&ldquo;Act&rdquo; means The Mizoram Water Supplies (Control) Act, 2004(No.11 of 2004);<br />
	&nbsp;&nbsp; &nbsp;b)&nbsp;&nbsp; &nbsp;&ldquo;consumer&rdquo; means any person or owner or occupier of any premises provided with House Water connection, Public Water Point or Hand Pump Tube Well by Public Health Engineering Department;<br />
	&nbsp;&nbsp; &nbsp;c)&nbsp;&nbsp; &nbsp;&ldquo;disconnection&rdquo; means stoppage of supply of water due to certain reason which requires payment of re-connection fee and other expenses if any;<br />
	&nbsp;&nbsp; &nbsp;d)&nbsp;&nbsp; &nbsp;&ldquo;casual water connection&rdquo; means the water connection for a short period not more than 1(one) week or 7(seven) days;<br />
	&nbsp;&nbsp; &nbsp;e)&nbsp;&nbsp; &nbsp;&ldquo;habitation&rdquo; means any place(s) where people are living permanently.<br />
	&nbsp;&nbsp; &nbsp;f)&nbsp;&nbsp; &nbsp;&ldquo;kilolitre&rdquo; means one thousand litres;<br />
	&nbsp;&nbsp; &nbsp;g)&nbsp;&nbsp; &nbsp;&ldquo;premises&rdquo; means any land or building;&nbsp;&nbsp; &nbsp;<br />
	&nbsp;&nbsp; &nbsp;h)&nbsp;&nbsp; &nbsp;&ldquo;reconnection&rdquo; means reconnecting the disconnected water supply on payment of reconnection fee;<br />
	&nbsp;&nbsp; &nbsp;i)&nbsp;&nbsp; &nbsp;&ldquo;suspension&rdquo; means stoppage of supply of water for a certain period as notified in the suspension order. No need for&nbsp; payment of reconnection fee, but required payment of expenses if any,<br />
	&nbsp;&nbsp; &nbsp;j)&nbsp;&nbsp; &nbsp;&ldquo;temporary water connection&rdquo; means the water connection for a period more than 1(one) week but not exceeding 3(three) months;<br />
	&nbsp;&nbsp; &nbsp;k)&nbsp;&nbsp; &nbsp;&ldquo;Supply Tank&rdquo; means water tank(s) from where pipe(s) of house water connection(s) or Public Water Point(s) or Hydrant(s) are connected.<br />
	&nbsp;&nbsp; &nbsp;l)&nbsp;&nbsp; &nbsp;&ldquo;T-Cluster&rdquo; means point(s) on the water distribution pipe line(s) or end of water distribution pipe line(s) from where pipe(s) of house water connection(s) or Public&nbsp; Water Point(s) or hydrant(s) are connected.<br />
	&nbsp;&nbsp; &nbsp;m)&nbsp;&nbsp; &nbsp;&ldquo;Catchment area&rdquo; means the area of land draining into the source of water as notified by the Executive Engineer of the concerned Division as reserved catchment area.<br />
	&nbsp;&nbsp; &nbsp;m)&nbsp;&nbsp; &nbsp;&ldquo;Water Source&rdquo; means the source of water&nbsp; notified by the Executive Engineer of the concerned area as reserved water source.<br />
	(2)&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;All other words and expressions used herein and not defined shall have the meanings respectively assigned&nbsp; to them in the Act.<br />
	3.&nbsp;&nbsp; &nbsp;Conditions for provisions of water connection :-<br />
	&nbsp;&nbsp; &nbsp;(i)&nbsp;&nbsp; &nbsp;New water connection shall be provided only from Supply Tank or T-Cluster and the point of connection should be decided by the Department and not by the applicant.<br />
	&nbsp;&nbsp; &nbsp;(ii)&nbsp;&nbsp; &nbsp;Normally 1(one) House Water Connection is meant for 1(one) house hold or 1(one) family.&nbsp; Sharing of 1(one) house water connection by 2( two) or more families or house hold is not allowed. Generally 20mm diameter of G.I. Pipe (Medium Quality) ISI Marked or Bureau of Indian Standard Quality should be used for house water connection.&nbsp; If bigger diameter is to be used prior approval of concerned Superintending Engineer is to be obtained.<br />
	&nbsp;&nbsp; &nbsp;(iii)&nbsp;&nbsp; &nbsp;The application form for any type of house water connections&nbsp; viz. temporary water connection, permanent water connection and casual&nbsp; water connection as the case may be,as set out in Annexures-&nbsp; &lsquo;I(A)&rsquo;,&lsquo;I(B)&rsquo; &lsquo;II&rsquo; &amp; &lsquo;III&rsquo;&nbsp; be obtained from the concerned Executive Engineer or Sub-Divisional Officer in their office during office working&nbsp; hours.&nbsp; The application is to be submitted to the concerned Junior Engineer/Sectional Officer of the Department after duly filled up and should be accompanied by attested photo copy of Land Settlement Certificate(LSC) or any other relevant document or land pass issued by authority.&nbsp; On receipt of the application with all the necessary documents from the applicant, the concerned field staff shall conduct spot&nbsp; verification for feasibility.&nbsp; After the Department decide&nbsp; the point or location where the connection pipeline is to be connected, the Department shall accord the sanction.&nbsp; If the location or place is to be changed after the sanction is accorded, the applicant shall submit a fresh application with all the connected documents and the Department shall make verification and if found feasible a fresh sanction shall be accorded.<br />
	&nbsp;&nbsp; &nbsp;(iv)&nbsp;&nbsp; &nbsp;Superintending Engineer of the concerned Circle, where Superintending Engineer and Executive Engineer are in the same station shall sanction the permanent water connection. However, where the Superinteding Engineer and Executive Engineer are not in the same station, the Executive Engineer concerned may accord the sanction for the same. Executive Engineer of the Division shall sanction the Temporary and Casual water connection, where the Divisional Headquarters and Sub-Divisional Headquarters are in the same station.&nbsp; However, where the Divisional Headquaters and Sub-Divisional Headquarters are not in the same station, Sub-Divisional Officer of the concerned Sub-Division shall accord the sanction for the same.<br />
	<br />
	&nbsp;&nbsp; &nbsp;(v)&nbsp;&nbsp; &nbsp;All types of fitting and fixing of G.I.Pipes&nbsp; while giving water connection either permanent or temporary or casual, shall be done by&nbsp; the Department only after all the required amount are deposited to the Department, the applicant shall be responsible for making settlement with the owner of&nbsp; the property through which the pipes have to be installed and payment of all the compensation wherever necessary for all possible damage caused to the public as well as private property due to the laying of pipes for giving water connection to the applicant. The applicant for the temporary and casual connection shall arrange all the necessary materials required for giving the said connection. If the applicant is unable to provide the necessary materials, the Department may provide the same after the cost of the said materials as fixed from time to time by the Department is deposited by the applicant.<br />
	<br />
	4.&nbsp;&nbsp; &nbsp;Disconnection of water connection and suspension of water supply.<br />
	&nbsp;&nbsp; &nbsp;1)&nbsp;&nbsp; &nbsp;The concerned Executive Engineer and the Sub Divisional Officer are authorized to disconnect and suspend water supply without notice as and when the consumer violates any one of the provisions of&nbsp; Section14(1) (a) to (h) of the Act.&nbsp; The reconnection&nbsp; of the disconnected house water connection and resumption of the suspended water supply&nbsp; shall be done as per the provision of&nbsp; Section 14(4), (5) and (6) of the Act.<br />
	&nbsp;&nbsp; &nbsp;2)&nbsp;&nbsp; &nbsp;In addition to the reasons given for disconnection of the water connection and the suspension of water supply in the Section 14(1)(a) to (h) of the Act, the concerned Executive Engineer and concerned Sub-Divisional Officer may disconnect water connection or suspend water supply for the following reasons:-<br />
	&nbsp;&nbsp; &nbsp;(i)&nbsp;&nbsp; &nbsp;if any living being viz. swarm of bees and pets like dogs, monkeys and other animals and the family members in the premises or land to&nbsp; which water connection&nbsp; is provided, cause any inconvenience to the Departmental Staff on duty by way of&nbsp; intimidating or endangering to the extent that operating work of water supply is severely disturbed.<br />
	&nbsp;&nbsp; &nbsp;(ii)&nbsp;&nbsp; &nbsp;if a consumer misuses the water supplied by the Department other than the purpose as specified in the Act.<br />
	&nbsp;&nbsp; &nbsp;(iii)&nbsp;&nbsp; &nbsp;if a consumer or owner of house water connection&nbsp; sells or doles out water supplied by the Department.<br />
	&nbsp;&nbsp; &nbsp;(iv)&nbsp;&nbsp; &nbsp;if a consumer or anybody representing the consumer refuses or does not permit installation of water metre in the&nbsp; water connection.<br />
	&nbsp;&nbsp; &nbsp;(v)&nbsp;&nbsp; &nbsp;if a consumer violates any instruction issued by the Department regarding shifting, modifying&nbsp; or rectifying&nbsp; the existing water connection due to the reasons the Department feels absolutely necessary.<br />
	&nbsp;&nbsp; &nbsp;(vi)&nbsp;&nbsp; &nbsp;if a consumer or anybody representing the consumer makes any complaint which the Department finds unjust and false.<br />
	&nbsp;&nbsp; &nbsp;(vii)&nbsp;&nbsp; &nbsp;if a consumer or anybody representing the consumer refuses to pay the cost of the water meter for replacement in the event of loss or damage of the water meter fitted to the water connection.<br />
	&nbsp;&nbsp; &nbsp;(viii)&nbsp;&nbsp; &nbsp;if a consumer forcibly instructs or directs&nbsp; the Departmental staff to operate water supply system for his or her own benefit affecting smooth distribution of water.<br />
	&nbsp;&nbsp; &nbsp;(ix)&nbsp;&nbsp; &nbsp;if a consumer or anybody representing the consumer does not take any action when there is leakage in the water connection which requires immediate action.<br />
	&nbsp;&nbsp; &nbsp;(x)&nbsp;&nbsp; &nbsp;if a building or house to which water conection has been made remains&nbsp; unoccupied more than 1(one) month the House Water Connection may be disconnected and if the same building is unoccupied for more than 1(one) week temporary suspension of water supply should be done.<br />
	&nbsp;&nbsp; &nbsp;(xi)&nbsp;&nbsp; &nbsp;if any consumer or owner of house water connection operates or used to operate any pipe fittings without the instruction or permission of the Department personel(s) who is or are authorised to operate that particular water supply.<br />
	5.&nbsp;&nbsp; &nbsp;Transfer of Water Connection :&nbsp; Transfer of Water Connection may be applied to the Executive Engineer of the concerned division in a prescribed form set out in Annexure- &lsquo;V&rsquo; as&nbsp; per the provisions of&nbsp; Section 15 of the Act.<br />
	&nbsp;6.&nbsp;&nbsp; &nbsp;Right of reservation of Water sources with the Catchment areas for human consumption: The Department may exercise the right to reserve any water source(s) including Ground Water with the catchment area(s) which is or are found suitable for human consumption for any habitation.&nbsp; No person, organisation, other department or other authority shall use or utilize water from the reserved source without prior permission of the Department. The Executive Engineer of the concerned Division is empowered to issue the notification of the reserved water source(s) and&nbsp; the Catchment area(s) within his or her own jurisdiction.<br />
	<br />
	7.&nbsp;&nbsp; &nbsp;Rate of water and other charges :<br />
	&nbsp;&nbsp; &nbsp;(1)&nbsp;&nbsp; &nbsp;A non-refundable connection fee of Rs.500/- (Rupees five hundred) only shall be charged for each new pipe water connection.<br />
	&nbsp;&nbsp; &nbsp;(2)&nbsp;&nbsp; &nbsp;A minimum of Rs.10 (Rupees ten) per kilolitre per piped water connection shall be charged as tariff for supply of maximum 10,000 (ten thousand) litres per month per piped water connection subject to a minimum charge of Rs.100/- (Rupees one hundred)only.<br />
	&nbsp;&nbsp; &nbsp;(3)&nbsp;&nbsp; &nbsp;A minimum of Rs.15(Rupees fifteen) per kilolitre per piped water connection shall be charged as tariff for supply of water in excess of&nbsp; 10,000 (ten thousand) litres per month but not exceeding 30,000 (thirty thousand) litres per month per piped water connection.<br />
	&nbsp;&nbsp; &nbsp;(4)&nbsp;&nbsp; &nbsp;A minimum of Rs.20(Rupees twenty) per kilolitre per piped water connection shall be charged as tariff for supply of water in excess of 30,000 (thirty thousand) litres per month per piped water connection.<br />
	&nbsp;&nbsp; &nbsp;(5)&nbsp;&nbsp; &nbsp;Rs. 40 (Rupees forty) only per kilolitre shall be charged if water is purchased from the Department depending upon the availability of water.<br />
	&nbsp;&nbsp; &nbsp;(6)&nbsp;&nbsp; &nbsp;Rs.10 (Rupees ten) only per month shall be charged to each family or household of consumer from Public point or Hand Pump Tube Wells within Mizoram where operation and maintenance of water supply is taken up by the Department.<br />
	&nbsp;&nbsp; &nbsp;(7)&nbsp;&nbsp; &nbsp;Rs.500 (Rupees five hundred) shall be charged as re-connection fee of disconnected water connection.<br />
	&nbsp;&nbsp; &nbsp;(8)&nbsp;&nbsp; &nbsp;Rs.100 (Rupees one hundred) shall be charged as connection fee for one Temporary water connection or Casual water connection.<br />
	&nbsp;&nbsp; &nbsp;(9)&nbsp;&nbsp; &nbsp;Rate of charges for supply of water to Temporary water connection or Casual water connection shall be as provided in sub-rules (2), (3) and (4) of rule 7.<br />
	&nbsp;&nbsp; &nbsp;(10)&nbsp;&nbsp; &nbsp;In the case of any alteration, modification or rectification of existing water connection, all the expenses should be borne by the applicant or consumer.<br />
	&nbsp;&nbsp; &nbsp;(11)&nbsp;&nbsp; &nbsp;The Department shall provide water meter to water connection as far as possible irrespective of whether the consumers ask for it or not.&nbsp; The Executive Engineer in charge of the Division is authorised for identification and for fitting water meter to any water connection.&nbsp; The reading of meter indicating the quantity of water supplied to the water connection shall be presumed correct unless the contrary is found, and in the case of dispute the decision of the Department shall be final.<br />
	&nbsp;&nbsp; &nbsp;(12)&nbsp;&nbsp; &nbsp;If any transfer application is submitted by the owner of water connection or consumer, the transfer of water connection shall be carried out by the Department provided that the sanction is accorded by the competent officer and the consumer deposits the transfer fee of Rs 200 (Rupees two hundred)only per one house water connection and any other charge required for transfer to the Department.<br />
	&nbsp;&nbsp; &nbsp;(13)&nbsp;&nbsp; &nbsp;Rent for Water Meter shall be charged at the rate of Rs.10(Rupees ten) per Water Meter per month for all sizes. &nbsp;<br />
	&nbsp;&nbsp; &nbsp;(14)&nbsp;&nbsp; &nbsp;All bills, fees and charges, pertaining to any water connection, once paid to the Department are non-refundable if work are already executed for the purpose.<br />
	&nbsp;&nbsp; &nbsp;(15)&nbsp;&nbsp; &nbsp;Transfer of ownership of water connection or changing name or alteration of name of the house water connection holder may&nbsp; be done subject to production of Land Settlement Certificate or any other relevant document issued by the Revenue authority in which the tranferee&rsquo;s name is entered and on production of document showing that all the dues are cleared. Application in prescribed form as per Annexure -VI shall be submitted to concerned Executive Engineer for sanction.<br />
	&nbsp;&nbsp; &nbsp;(16)&nbsp;&nbsp; &nbsp;If owner of Temporary water connection or Casual water connection apply for permanent water connection, the applicant shall submit fresh&nbsp; application as per the provisions of Section 4 of the Act and Rules 3, and the previous deposit for Temporary water connection or casual water connection may be deducted on production of relevant document. The Temporary water connection and casual water connection can be converted to permanent water connection within the respective validity period i.e. 3(three) months and 7(seven) days respectively.<br />
	&nbsp;&nbsp; &nbsp;(17)&nbsp;&nbsp; &nbsp;All the required amount i.e. estimate for water connection&nbsp; shall be paid by applicant to the concerned Division of the Department within the validity of the sanction as per Section 4 of the Act.&nbsp; If payment is not made within the specified period, revalidation may be done if applied by the applicant and the revalidation sanction shall supersede the previous sanction.&nbsp; Payment&nbsp; shall be made through Treasury Challan as specified by the Department.<br />
	&nbsp;&nbsp; &nbsp;(18)&nbsp;&nbsp; &nbsp;The owner of water connection or consumer shall pay all water bill by cash only to the specified place/counter as authorized by the concerned Executive Engineer of the Department.<br />
	&nbsp;&nbsp; &nbsp;(19)&nbsp;&nbsp; &nbsp;Such water bills and other charges shall be paid as per bill or card served to the consumers by the Department. &nbsp;<br />
	&nbsp;&nbsp; &nbsp;(20)&nbsp;&nbsp; &nbsp;A periodical water bill or charges or monthly water bill or charges shall be paid to the&nbsp; Department within 3(three) months or 90(ninety) days after handing over the bills or charges to the consumer or entering the bill amount or charge in the card.&nbsp;&nbsp; After expiry of the stipulated period the consumer or owner of water connection shall have to pay the bill along with the simple interest at the rate of 1% per month of the bill amount.<br />
	&nbsp;&nbsp; &nbsp;(21)&nbsp;&nbsp; &nbsp;Part payment of water bill or charges for less than one month is not permitted.<br />
	&nbsp;&nbsp; &nbsp;(22)&nbsp;&nbsp; &nbsp;Any charges for repairing, shifting, alteration, rectification or modification&nbsp; of water connection is to be borne by the consumer or owner of&nbsp; house water connection. The Department shall do the required work only after the consumer or the owner of the house water connection deposits the required amount to the Department.&nbsp; In the event of any private or&nbsp; public property to be damaged, the owner of water connection or applicant shall settle the matter before the Department starts the work and all the expenses required for re-installation and repair of damages shall be borne by the applicant or the owner of water connection or consumer.<br />
	&nbsp;&nbsp; &nbsp;(23)&nbsp;&nbsp; &nbsp;The Department may supply water to the owner of the house&nbsp; water connection or consumer at least once a week. If the water supplied in a month is less than 2000 litres&nbsp; ( two thousand litres) due to breakdown of the system of water supply scheme or willful negligence of Department personnel, the Department may consider a rebate of 50% of minimum water bill subject to verification of the Department on the genuiness of the quantity of water supplied .&nbsp; In order to get the rebate, the consumer or owner of house water connection shall make claim to the Department within 15(fifteen) days from the date of issue of the bill by the Department and any claim made thereafter shall not be entertained. If the Department inadvertently raise the water bill or charge for any&nbsp; month during which water is not supplied to the consumer or owner of the house water connection, the Executive Engineer of the concerned Division of the Department may waive the amount wrongly charged.<br />
	&nbsp;&nbsp; &nbsp;(24)&nbsp;&nbsp; &nbsp;If water meter is out of order, or the water meter is lost, the Department may take average quantity of water supplied or bills or charges during the last 3(three) months or any other appropriate mode to assess the quantity of water consumed and fix&nbsp; the reasonable amount to be paid by the consumer. The amount so fixed by the Department shall be final.<br />
	&nbsp;&nbsp; &nbsp;(25)&nbsp;&nbsp; &nbsp;The Department shall recover the cost of new water meter from the consumer or owner of the water connection for replacing the loss or damage of water meter which is fitted to the water connection if loss or damage is not caused by natural calamity.<br />
	&nbsp;&nbsp; &nbsp;(26)&nbsp;&nbsp; &nbsp;Pre-payment of any water bill for any house water connection is not allowed.<br />
	8.&nbsp;&nbsp; &nbsp;Procedure for initiating criminal proceeding for offences committed by any person<br />
	&nbsp;&nbsp; &nbsp;1)&nbsp;&nbsp; &nbsp;Criminal proceedings may be set on motion by filing in complaint by any officer of the Department not below the rank of Sub-Divisional Officer to the competent Judicial Magistrate.<br />
	&nbsp;&nbsp; &nbsp;2)&nbsp;&nbsp; &nbsp;The offences under Section 17 of the Act is triable by the Judicial Magistrate of the first class.<br />
	&nbsp;&nbsp; &nbsp;3)&nbsp;&nbsp; &nbsp;The Officers of the Department are public servant within the meaning of section 21 of the Indian Penal Code.<br />
	9.&nbsp;&nbsp; &nbsp;The manner and procedure of entertainment and disposal of disputes and Departmental appeals<br />
	&nbsp;&nbsp; &nbsp;1)&nbsp;&nbsp; &nbsp;If any disputes arises due to the action of the officers of the Department, the consumer may file a complaint in writing to the Executive Engineer of the concerned Division. On receipt of the complaint, the Executive Engineer or his representative on his behalf,&nbsp; shall conduct inquiry and hear the complainant and others involved in the dispute and pass necessary orders. No complaint, regarding excess meter reading and billing will be entertained by the Executive Engineer unless the complainant first pays the bills and attaches the receipt with the complaint. No complaint shall be entertained after expiry of 30 days.<br />
	&nbsp;&nbsp; &nbsp;2)&nbsp;&nbsp; &nbsp;The consumer may file an appeal against the decision/ order made under sub-rule 1 of Rule 9 to the higher authorities of Public Health Engineering Department within 15 days from the date of communication to him/her of such decision or order.<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;i)&nbsp;&nbsp; &nbsp;Every memorandum of appeal shall be accompanied by a copy of the decision or order appealed against.<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;ii)&nbsp;&nbsp; &nbsp;Every appeal under this rule shall be filed in such form and in such manner as may be specified by way of notification by the Chief Engineer, Public Health Engineering Department, Government of Mizoram.<br />
	&nbsp;&nbsp; &nbsp;3)&nbsp;&nbsp; &nbsp;An appeal under sub-rule (2) shall be proceeded as follows:<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;i)&nbsp;&nbsp; &nbsp;The Appellate Authority shall give an opportunity to the appelant to be heard in person, if he so desires.<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;ii)&nbsp;&nbsp; &nbsp;The Appellate Authority may, at the hearing of an appeal allow the appellant to go into any ground of appeal not specified in the grounds of appeal, if the Appellate Authority is satisfied that omission of that ground from the grounds of appeal was not willful or unreasonable.<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;iii)&nbsp;&nbsp; &nbsp;The Appellate Authority may, after making such further inquiry as may be necessary, pass such orders as it thinks fit, confirming, modifying or annulling the decision or order appealed against.<br />
	&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;iv)&nbsp;&nbsp; &nbsp;The order of the Appellate Authority disposing of the appeal under this rule shall be in writing and shall state the points for determination&nbsp; reasons for the decision, and the decision there in.<br />
	<br />
	<br />
	<br />
	10.&nbsp;&nbsp; &nbsp;Manner of maintenance of records, returns and prescription of forms necessary thereof :<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - I (A)&nbsp;&nbsp; &nbsp;: &nbsp;&nbsp; &nbsp;Form of application of&nbsp; Permanent Water&nbsp; connection. (Private)<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - I (B) &nbsp;&nbsp; &nbsp;:&nbsp;&nbsp; &nbsp;Form of application of Permanent Water&nbsp; connection. (Government / Organisation )<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - II &nbsp;&nbsp; &nbsp;:&nbsp;&nbsp; &nbsp;Form of application of Temporary Water connection.<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - III &nbsp;&nbsp; &nbsp;:&nbsp;&nbsp; &nbsp;Form of application of Casual Water connection.<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - IV &nbsp;&nbsp; &nbsp;:&nbsp;&nbsp; &nbsp;Form of application for re-connection of disconnected water connection.<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - V&nbsp;&nbsp; &nbsp;:&nbsp;&nbsp; &nbsp;Form of application for transfer of house water connection.<br />
	&nbsp;&nbsp; &nbsp;ANNEXURE - VI &nbsp;&nbsp; &nbsp;:&nbsp;&nbsp; &nbsp;Form of application for changing of consumer&rsquo;s name.</p>
	@endsection